# Execution control packages
---
sip:

  execution_control:

    # Master Controller
    master_controller:
      title: Master Controller Service

      rpc:
        title: Master Controller (RPyC flavour)

      tango:
        title: Master Controller (Tango Element Master)

    # Monitoring Service
    monitoring:
      title: Monitoring service

    # Processing Controller Service
    processing_controller:
      title: Processing Controller

      rpc:
        title: Processing Controller (RPyC flavour)

      tango:
        title: Processing Controller (Tango device server)

