# Execution control packages
---
sip:

  execution_control:

    # Master Controller
    master_controller:
      title: Master Controller Service

      rpc:
        title: Master Controller (RPyC flavour)

      tango:
        title: Master Controller (Tango Element Master)

    # Processing Controller
    processing_controller:
      title: Processing Controller Service


    # Processing Block
    processing_block:
      title: Processing Block Controller

      rpc:
        title: Processing Block (RPyC flavour)

      tango:
        title: Processing Block (Tango device server)

    # Tango Logger
    tango_logger:
      title: Element Tango Logger

    # Monitoring Service
    monitoring_service:
      title: Monitoring service

    # Configuration Service
    configuration_service:
      title: Configuration Service

      redis:
        title: Redis Configuration Service
