# Execution control packages
---
sip:

  execution_control:

    # Master Controller
    master:
      title: Master Controller Service

      rpc:
        title: RPC Master Controller Service
        desc:
        abbr: master_rpc

      tango:
        title: Tango Element Master
        desc:
        abbr: master_tango

    # Processing Controller
    processing_controller:
      title: Processing Controller Service

      rpc:
        title: RPC Processing Controller Service
        desc:
        abbr: pctl_rpc

      tango:
        title: Tango Processing Controller
        desc:
        abbr: pctl_tango

    # Processing Block Controller
    processing_block_controller:
      title: Processing Block Controller
      desc:
      abbr:

    # Tango Logger
    tango_logger:
      title: Element Tango Logger
      desc:
      abbr: tango_logger


    # Monitoring Service
    monitoring_service:
      title: Monitoring service
      desc:
      abbr: sdp_mon

    # Configuration Service
    configuration_service:
      title: Configuration Service

      redis:
        title: Redis Configuration Service
        desc: Simple Configuration service using Redis
        abbr: config_redis
