# SDP services
---
package_root: ['sip', 'sdp_services']

packages:

  - title: Quality Assessment Service
    path:  quality_assessment_tango
    desc:  Quality Assessment Service (Tango device)
    abbr:  qa_tango

  - title: Buffer Management Service
    path:  buffer_manager
    desc: Buffer management service
    abbr: buffer_manager