# SDP services
---
sip:

  sdp_services:

    quality_assessment:
      title: Quality Assessment Service

    global_sky_model:
      title: Global Sky Model Service

    science_data_model:
      title: Science Data Model Service
