# Execution Frameworks
---
package_root: ['sip', 'execution_framework']

packages:

  - title: Execution Framework Interface Service
    path: exec_framework_interface
    desc: Execution Framework Interface Service
    abbr: ef_interface

  - title:
    path:
    desc:
    abbr: