version: "3.3"
services:
  file_writer:
    image: ingest_test
    volumes:
      - type: volume
        source: my-test
        target: /app/output
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - "6060:9999/udp"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
        reservations:
          cpus: '0.1'
          memory: 20M
      restart_policy:
        condition: none
volumes:
    my-test:
        external: True
