version: "3.3"
services:
  file_writer:
    image: sip
    command: /home/util/ingest_test/udp_recv.py
    volumes:
      - type: volume
        source: my-test
        target: /home/sdp/output
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - "6060:9999/udp"
    netowrk:
      - sip
    deploy:
      replicas: 1
      restart_policy:
        condition: none
volumes:
    my-test:
        external: True

networks:
  sip:
      external: True
