#
# Usage:
#   docker-compose build [service name]
#

version: '3.3'

services:

  # SIP docker image.
  sip:
    image: skasip/sip
    build:
      context: .
      dockerfile: ./sip/Dockerfile

  # ZeroMQ logging aggregator
  zla:
    image: skasip/zla
    build:
      context: ./sip/zmq_logging_aggregator
      dockerfile: Dockerfile

  # (Mock) ZeroMQ logging publisher
  zlp:
    image: skasip/zlp
    build:
      context: ./sip
      dockerfile: zmq_logging_publisher/Dockerfile
