#
# Usage:
#   docker-compose build [service name]
#

version: '3.3'

services:

  # Master Controller (RPyC)
  master_controller_rpyc:
    image: skasip/master_rpyc
    build:
      context: sip/execution_control/master_controller/rpyc
      dockerfile: Dockerfile
    ports:
      - target: 12345     # port inside the container
        published: 12345  # publicly exposed port

  # Master Controller (RPyC)
  quality_assessment_rpyc:
    image: skasip/qa_rpyc
    build:
      context: sip/sdp_services/quality_assessment/rpyc
      dockerfile: Dockerfile
    ports:
      - target: 12345     # port inside the container
        published: 12346  # publicly exposed port
