#
# Usage:
#   docker-compose build [service name]
#

version: '3.3'

services:

  # SIP docker image.
  sip:
    image: sip
    build:
      context: .
      dockerfile: ./sip/Dockerfile

  # ZeroMQ logging aggregator
  zla:
    image: sip/zla
    build:
      context: ./sip/zmq_logging_aggregator
      dockerfile: Dockerfile

  # ZeroMQ logging aggregator
  zlp:
    image: sip/zlp
    build:
      context: ./sip/zmq_logging_aggregator/tests/mock_log_publisher
      dockerfile: Dockerfile
