#
# Usage:
#   docker-compose build [service name]
#

version: '3.3'

services:

  # SIP docker image.
  sip:
    image: skasip/sip
    build:
      context: .
      dockerfile: ./sip/Dockerfile

  # ZeroMQ logging subscriber
  zlogs:
    image: skasip/zlogs
    build:
      context: ./sip/zmq_logging_subscriber
      dockerfile: Dockerfile

  # (Mock) ZeroMQ logging forwarder (proxy)
  zlogf:
    image: skasip/zlogf
    build:
      context: ./sip/zmq_logging_forwarder
      dockerfile: Dockerfile

  # (Mock) ZeroMQ logging publisher
  # Note: Needs SIP as context to get the handler client.
  zlogp:
    image: skasip/zlogp
    build:
      context: ./sip
      dockerfile: zmq_logging_publisher/Dockerfile
