---
# file: docker_swarm.info/tasks/main.yml

- name: Determine swarm status
  shell: >
    docker info | egrep '^Swarm: ' | cut -d ' ' -f2
  register: swarm_status

# - name: Display the swarm status if using -v.
#   debug:
#     var: swarm_status
#     verbosity: 1

# - name: Report if the host is already part of a swarm.
#   debug:
#     msg: "{{ inventory_hostname }} swarm status {{ swarm_status.stdout }}"
