---

# Install python 2 on all hosts (needed for ansible)
- name: Make sure python2 is installed on the nodes (needed for ansible)
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

