---
# Run with: ansible-playbook -i hosts --private-key=keys/sip sip.yml

# Download and install SIP code.
- name: Download and install SIP
  hosts: all
  become_method: sudo
  roles:
    - role: ska.sip
      sip_branch: spark_imager_test
