---
# Run with: ansible-playbook -i hosts playbook.yml

## Install Python 2
#- hosts: all
#  gather_facts: false
#  remote_user: ubuntu
#  become_method: sudo
#  become: true
#  tasks:
#    - name: install python 2
#      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
#
## Install Docker on all nodes
## https://galaxy.ansible.com/angstwad/docker_ubuntu/
#- name: Install docker and reboot
#  hosts: all
#  remote_user: ubuntu
#  become_method: sudo
#  become: yes
#  roles:
#    - role: angstwad.docker_ubuntu
#      docker_apt_cache_valid_time: 3600
#      install_docker_py_on_1604: true
#      update_docker_package: true
#      docker_group_members: [ ubuntu ]
#    - role: GROG.reboot

 # Install SIP code.
- name: Install SIP
  hosts: all
  remote_user: ubuntu
  become_method: sudo
  vars:
    - sip_branch: vagrant-ansible
  roles:
    - role: ska.sip
