---
# https://stackoverflow.com/questions/40316836/update-bashrc-with-virtualenv-info-using-ansible

- name: Linux env configuration
  hosts: all
  tasks:
    - name: Update .bashrc with better command search
      blockinfile:
        dest: "{{ ansible_env.HOME }}/.bashrc"
        block: |
          bind '"\e[A": history-search-backward'
          bind '"\e[B": history-search-forward'
        marker: '# {mark} ANSIBLE MANAGED BLOCK - -'
        insertafter: EOF
        create: yes
