---
# file: oskar_python/tasks/main.yml

# - name: Install oskar python dependencies
#   become: yes
#   yum:
#     name: "{{ item }}"
#     state: installed
#   with_items:
#     - python2-pip

- easy_install:
    name: pip
    state: latest
  become: yes

- pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - setuptools
    - numpy
  become: yes

- pip:
    name: file:///home/vagrant/oskar.git/python
  become: yes