---
# file: oskar_python/tasks/main.yml

- easy_install:
    name: pip
    state: latest
  become: yes

- pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - setuptools
    - numpy
  become: yes

- pip:
    name: file:///home/vagrant/oskar.git/python
  become: yes
