version: "3.3"

services:

  vis_ingest1:
    image: njthykkathu/sip
    entrypoint: python3 -m
    command: sip.emulators.csp_visibility_sender -v /home/sdp/sip/etc/vis_sender_config.json
    networks:
      - outside
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.sip_worker4 == true
      labels:
        com.dn.description: "Host networking"

  vis_ingest2:
    image: njthykkathu/sip
    entrypoint: python3 -m
    command: sip.emulators.csp_visibility_sender -v /home/sdp/sip/etc/vis_sender_config1.json
    networks:
      - outside
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.sip_worker5 == true
      labels:
        com.dn.description: "Host networking"

  vis_ingest3:
    image: njthykkathu/sip
    entrypoint: python3 -m
    command: sip.emulators.csp_visibility_sender -v /home/sdp/sip/etc/vis_sender_config2.json
    networks:
      - outside
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.sip_worker6 == true
      labels:
        com.dn.description: "Host networking"

networks:
  outside:
    external:
      name: "host"

