#
# https://github.com/nailor/kafka-python-demo
# https://ngeor.wordpress.com/2017/03/25/kafka-with-docker-a-docker-introduction/
# https://qagurusite.wordpress.com/2017/04/15/how-to-use-kafka-in-docker-compose/
#
# **********
# http://zablo.net/blog/post/setup-apache-kafka-in-docker-on-windows
# **********
# https://gist.github.com/abacaphiliac/f0553548f9c577214d16290c2e751071
#

version: '3.4'

services:

  kafkaserver:
    image: spotify/kafka
    container_name: kafka
    hostname: kafkaserver
    networks:
      - kafkanet
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafkaserver
      ADVERTISED_PORT: 9092

  kafkamanager:
    image: mzagar/kafka-manager-docker:1.3.3.4
    container_name: kafkamanager
    networks:
      - kafkanet
    ports:
      - 9000:9000
    links:
      - kafkaserver
    environment:
      ZK_HOSTS: "kafkaserver:2181"

networks:
  kafkanet:
    driver: overlay
