---
# file: docker_swarm.jon/tasks/main.yml

# - name: zzz
#   debug:
#     var: hostvars
#
# - name: xxx
#   debug:
#     msg: ">> {{ inventory_hostname }} swarm status {{ swarm_status.stdout }}"

# - name: zzz
#   debug:
#     var: swarm_manager_ip
#
# - name: zzz
#   debug:
#     var: swarm_manager_token

# - name: Join worker nodes to the cluster
#   shell: >
#     docker swarm join
#     --advertise-addr={{ swarm_iface }}:2377
#     --token={{ swarm_manager_token }}
#     {{ swarm_manager_ip }}:2377
#   when: "'inactive' in swarm_status.stdout_lines"

- name: Join worker nodes to the cluster
  shell: >
    docker swarm join
    --token={{ token }}
    {{ leader_ip }}:2377
  when: "'inactive' in swarm_status.stdout_lines"


#
