version: "3.3"

services:

  vr:
    # image: njthykkathu/sip:latest
    image: njthykkathu/vis_test:latest
    entrypoint: python3
    command: /home/sdp/receiver/recv_vis_data.py /home/sdp/receiver/vis_receiver_config.json
    volumes:
      - type: volume
        source: vis-vol1
        target: /home/sdp/output
    networks:
      - outside
    deploy:
      replicas: 1
      restart_policy: 
        condition: none
      placement:
        constraints:
          - node.labels.sip_worker1 == true
      labels:
        com.dn.description: "Host networking"

networks:
  outside:
    external:
      name: "host"

volumes:
    vis-vol1:
        external: True
