---
# file: cascore/tasks/main.yml

- name: Install casacore dependencies
  become: yes
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - gcc-gfortran
    - flex
    - bison
    - blas
    - blas-devel
    - lapack
    - lapack-devel
    - cfitsio
    - cfitsio-devel
    - wcslib
    - wcslib-devel
    - boost
    - boost-devel
    - fftw
    - fftw-devel
    # - python-devel
    # - hdf5
    # - hdf5-devel
    # - numpy
    # - boost-python
    # - ncurses
    # - ncurses-devel
    # - readline
    # - readline-devel

- name: Get the latest release of CASACORE
  git:
    repo: 'https://github.com/casacore/casacore.git'
    dest: casacore.git
    update: yes
    version: v2.3.0

- name: Create build directory (if needed)
  file:
    path: casacore.git/build
    state: directory

- name: Run CMake
  command: cmake3 .. -DMODULE=ms -DBUILD_PYTHON=OFF -DBUILD_TESTING=OFF -DUSE_HDF5=OFF -DUSE_THREADS=ON -DUSE_FFTW3=ON
  args:
    chdir: casacore.git/build

- name: Run make
  command: make -j8 all
  args:
    chdir: casacore.git/build

- make:
    chdir: casacore.git/build
    target: install
  become: yes
