version: 1
disable_existing_loggers: false

loggers:
  sip:
    level: DEBUG
    handlers: [console]

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: format1
    stream: ext://sys.stdout

formatters:
  format1:
    format: "> [%(levelname).3s] %(message)-50s (%(name)s:L%(lineno)i)"
