---
# file: docker_swarm.init/tasks/main.yml

- name: Initialize swarm cluster
  shell: >
    docker swarm init --advertise-addr={{ swarm_iface }}:2377
  when: "'inactive' in swarm_status.stdout_lines"

- name: Retrieve swarm worker token
  shell: docker swarm join-token -q worker
  register: swarm_worker_token
  run_once: True

- name: Retrieve swarm manager token
  shell: docker swarm join-token -q worker
  register: swarm_manager_token
  run_once: True

- name: Save swarm leader IP
  set_fact:
    swarm_leader_ip: "{{ ansible_host }}"
  run_once: True
