version: "3.3"

services:

  vs1:
    image: njthykkathu/vis_test:latest
    entrypoint: python3 -m
    command: csp_visibility_sender -v /home/sdp/csp_visibility_sender/vis_sender_config.json
    networks:
      - outside
    deploy:
      replicas: 1
      restart_policy: 
        condition: none
      placement:
        constraints:
          - node.labels.sip_worker4 == true
      labels:
        com.dn.description: "Host networking"

  vs2:
    image: njthykkathu/vis_test:latest
    entrypoint: python3 -m
    command: csp_visibility_sender -v /home/sdp/csp_visibility_sender/vis_sender_config2.json
    networks:
      - outside
    deploy:
      replicas: 1
      restart_policy: 
        condition: none
      placement:
        constraints:
          - node.labels.sip_worker5 == true
      labels:
        com.dn.description: "Host networking"

  vs3:
    image: njthykkathu/vis_test:latest
    entrypoint: python3 -m
    command: csp_visibility_sender -v /home/sdp/csp_visibility_sender/vis_sender_config3.json
    networks:
      - outside
    deploy:
      replicas: 1
      restart_policy: 
        condition: none
      placement:
        constraints:
          - node.labels.sip_worker6 == true
      labels:
        com.dn.description: "Host networking"

networks:
  outside:
    external:
      name: "host"

