version: "3.3"

services:

  vs:
    image: njthykkathu/vis_test:latest
    entrypoint: python3 -m
    # command: sip.emulators.csp_visibility_sender -v /home/sdp/sip/etc/vis_sender_config.json
    command: sender.csp_visibility_sender -v /home/sdp/sender/csp_visibility_sender/vis_sender_config.json
    networks:
      - outside
    deploy:
      replicas: 1
      restart_policy: 
        condition: none
      placement:
        constraints:
          - node.labels.sip_worker2 == true
      labels:
        com.dn.description: "Host networking"

networks:
  outside:
    external:
      name: "host"

