version: "3.3"

services:

  vis_ingest1:
    image: njthykkathu/sip
    entrypoint: python3
    command: /home/sdp/sip/tasks/tests/example_recv_vis_data.py /home/sdp/sip/etc/vis_receiver_config.json
    volumes:
      - type: volume
        source: vis-vol1
        target: /home/sdp/output
    networks:
      - outside
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.sip_worker1 == true
      labels:
        com.dn.description: "Host networking"

  vis_ingest2:
    image: njthykkathu/sip
    entrypoint: python3
    command: /home/sdp/sip/tasks/tests/example_recv_vis_data.py /home/sdp/sip/etc/vis_receiver_config.json
    volumes:
      - type: volume
        source: vis-vol2
        target: /home/sdp/output
    networks:
      - outside
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.sip_worker2 == true
      labels:
        com.dn.description: "Host networking"

  vis_ingest3:
    image: njthykkathu/sip
    entrypoint: python3
    command: /home/sdp/sip/tasks/tests/example_recv_vis_data.py /home/sdp/sip/etc/vis_receiver_config.json
    volumes:
      - type: volume
        source: vis-vol3
        target: /home/sdp/output
    networks:
      - outside
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.sip_worker3 == true
      labels:
        com.dn.description: "Host networking"

networks:
  outside:
    external:
      name: "host"

volumes:
    vis-vol1:
        external: True
    vis-vol2:
        external: True
    vis-vol3:
        external: True
