version: "3.3"

services:

  vis_ingest1:
    image: vis_ingest
    volumes:
      - type: volume
        source: vis-vol1
        target: /home/sdp/output
    networks:
      - outside
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ska1
      labels:
        com.dn.description: "Host networking"

  vis_ingest2:
    image: vis_ingest
    volumes:
      - type: volume
        source: vis-vol2
        target: /home/sdp/output
    networks:
      - outside
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ska2
      labels:
        com.dn.description: "Host networking"

  vis_ingest3:
    image: vis_ingest
    volumes:
      - type: volume
        source: vis-vol3
        target: /home/sdp/output
    networks:
      - outside
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ska3
      labels:
        com.dn.description: "Host networking"

networks:
  outside:
    external:
      name: "host"

volumes:
    vis-vol1:
        external: True
    vis-vol2:
        external: True
    vis-vol3:
        external: True
