version: "3.3"

services:

  vis_ingest1:
    image: sip
    entrypoint: python3
    command: /home/sdp/sip/tasks/tests/example_recv_vis_data.py /home/sdp/sip/etc/vis_receiver_config.json
    volumes:
      - type: volume
        source: vis-vol1
        target: /home/sdp/output
    networks:
      - outside
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ska1
      labels:
        com.dn.description: "Host networking"



networks:
  outside:
    external:
      name: "host"

volumes:
    vis-vol1:
        external: True
