version: "3.3"

services:

  vr1:
    image: njthykkathu/sip:latest
    entrypoint: python3
    command: /home/sdp/sip/tasks/tests/example_recv_vis_data.py /home/sdp/sip/etc/vis_receiver_config.json
    volumes:
      - type: volume
        source: vis-vol2
        target: /home/sdp/output
    networks:
      - outside
    deploy:
      replicas: 1
      restart_policy: 
        condition: none
      placement:
        constraints:
          - node.labels.sip_worker6 == true
      labels:
        com.dn.description: "Host networking"


networks:
  outside:
    external:
      name: "host"

volumes:
    vis-vol2:
        external: True
